module.exports = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#101415',
        'surface-bright': '#363a3b',
        'on-secondary-fixed': '#111c2d',
        'on-error-container': '#ffdad6',
        'threat-emerald': '#10B981',
        'secondary-container': '#3e495d',
        error: '#ffb4ab',
        'on-tertiary-container': '#738298',
        'secondary-fixed': '#d8e3fb',
        'charcoal-950': '#0A0A0A',
        'on-secondary-container': '#aeb9d0',
        'on-background': '#e0e3e5',
        'tertiary-fixed-dim': '#b9c7e0',
        'inverse-surface': '#e0e3e5',
        'on-primary-fixed': '#131b2e',
        'critical-sapphire': '#0EA5E9',
        'error-container': '#93000a',
        'inverse-primary': '#565e74',
        'surface-container-highest': '#323537',
        tertiary: '#b9c7e0',
        'zinc-400': '#A1A1AA',
        'primary-fixed': '#dae2fd',
        'surface-container-low': '#191c1e',
        'slate-900': '#0F172A',
        'on-tertiary-fixed': '#0d1c2f',
        'primary-container': '#0f172a',
        'on-secondary': '#263143',
        'on-surface-variant': '#c6c6cd',
        'secondary-fixed-dim': '#bcc7de',
        'surface-container-high': '#272a2c',
        'primary-fixed-dim': '#bec6e0',
        outline: '#909097',
        'on-tertiary': '#233144',
        'surface-container-lowest': '#0b0f10',
        'on-primary-container': '#798098',
        'surface-container': '#1d2022',
        'on-primary-fixed-variant': '#3f465c',
        'surface-variant': '#323537',
        'tertiary-container': '#09182a',
        secondary: '#bcc7de',
        'on-primary': '#283044',
        'surface-tint': '#bec6e0',
        'on-secondary-fixed-variant': '#3c475a',
        'outline-variant': '#45464d',
        primary: '#bec6e0',
        'on-tertiary-fixed-variant': '#3a485c',
        'border-subtle': 'rgba(255, 255, 255, 0.08)',
        'inverse-on-surface': '#2d3133',
        'on-error': '#690005',
        surface: '#101415',
        'tertiary-fixed': '#d5e3fd',
        'on-surface': '#e0e3e5',
        background: '#101415',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '16px',
        'sidebar-width': '260px',
        'card-gap': '24px',
        'container-padding': '32px',
        unit: '4px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
